In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("customer behavior.csv", sep=";")

print("DATA AWAL:")
display(df)

DATA AWAL:

,Customer ID,Gender,Age,City,Membership Type,Total Spend,Items Purchased,Average Rating,Discount Applied,Days Since Last Purchase,Satisfaction Level
0,101,Female,29,New York,Gold,11202,14,46,True,25,Satisfied
1,102,Male,34,Los Angeles,Silver,7805,11,41,False,18,Neutral
2,103,Female,43,Chicago,Bronze,51075,9,34,True,42,Unsatisfied
3,104,Male,30,San Francisco,Gold,14803,19,47,False,12,Satisfied
4,105,Male,27,Miami,Silver,7204,13,4,True,55,Unsatisfied
...,...,...,...,...,...,...,...,...,...,...,...
345,446,Male,32,Miami,Silver,6603,10,38,True,42,Unsatisfied
346,447,Female,36,Houston,Bronze,4705,8,3,False,27,Neutral
347,448,Female,30,New York,Gold,11908,16,45,True,28,Satisfied
348,449,Male,34,Los Angeles,Silver,7802,11,42,False,21,Neutral
349,450,Female,43,Chicago,Bronze,51575,10,33,True,49,Unsatisfied

In [3]:
df.duplicated().sum()

df = df.drop_duplicates()

In [4]:
#karena skala rating 1-50 dan ada yang hanya satu digit saja dan polanya pasti dibawah angka 5 berarti pola nol dibelakng hilang yang cukup masuk akal

df["Average Rating"] = df["Average Rating"].apply(
    lambda x: x * 10 if x < 10 else x
)

In [5]:
df.isnull().sum()

Customer ID                 0
Gender                      0
Age                         0
City                        0
Membership Type             0
Total Spend                 0
Items Purchased             0
Average Rating              0
Discount Applied            0
Days Since Last Purchase    0
Satisfaction Level          2
dtype: int64

In [6]:
df = df.fillna({
    "Gender": "Unknown",
    "City": "Unknown",
    "Membership Type": "Unknown",
    "Average Rating": df["Average Rating"].median(),
    "Satisfaction Level": "Unknown"
})

In [7]:
df.isnull().sum()

Customer ID                 0
Gender                      0
Age                         0
City                        0
Membership Type             0
Total Spend                 0
Items Purchased             0
Average Rating              0
Discount Applied            0
Days Since Last Purchase    0
Satisfaction Level          0
dtype: int64

In [8]:
Q1 = df["Total Spend"].quantile(0.25)
Q3 = df["Total Spend"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

df["Outlier_TotalSpend"] = df["Total Spend"].apply(
    lambda x: "YES" if x < lower_bound or x > upper_bound else "NO"
)

print("\nDETEKSI OUTLIER TOTAL SPEND:")
display(df[["Customer ID", "Total Spend", "Outlier_TotalSpend"]])

DETEKSI OUTLIER TOTAL SPEND:

     Customer ID  Total Spend Outlier_TotalSpend
0            101        11202                 NO
1            102         7805                 NO
2            103        51075                YES
3            104        14803                 NO
4            105         7204                 NO
..           ...          ...                ...
345          446         6603                 NO
346          447         4705                 NO
347          448        11908                 NO
348          449         7802                 NO
349          450        51575                YES

[350 rows x 3 columns]

In [9]:
outlier_count = df[df["Outlier_TotalSpend"] == "YES"].shape[0]
print("Jumlah Outlier:", outlier_count)

Jumlah Outlier: 58

In [10]:
df = df.drop(columns=["Outlier_TotalSpend"])

bukan outlier secara bisnis konteks, karena jumlah spend yang masih wajar dan masih mungkin dalam sebuah pembelian, jadi yg saya ubah hanya rating, dan mengisi null yang kosong pada tingkat kepuasan secara unknown, tidak ada duplikat

In [11]:
# Kolom patokan duplikat
cols_to_check = ['Age', 'City', 'Items Purchased', 'Satisfaction Level', 'Membership Type','Average Rating']

# Hapus duplikat (menyimpan baris pertama dari setiap kombinasi)
df_cleaned = df.drop_duplicates(subset=cols_to_check, keep='first')

print("Data setelah duplikat dihapus:")
print(df_cleaned)

Data setelah duplikat dihapus:
     Customer ID  Gender  Age           City Membership Type  Total Spend  \
0            101  Female   29       New York            Gold        11202
1            102    Male   34    Los Angeles          Silver         7805
2            103  Female   43        Chicago          Bronze        51075
3            104    Male   30  San Francisco            Gold        14803
4            105    Male   27          Miami          Silver         7204
5            106  Female   37        Houston          Bronze         4408
6            107  Female   31       New York            Gold        11506
7            108    Male   35    Los Angeles          Silver         8009
8            109  Female   41        Chicago          Bronze        49525
9            110    Male   28  San Francisco            Gold        15201
10           111    Male   32          Miami          Silver         6903
11           112  Female   36        Houston          Bronze         4705
12           113  Female   30       New York            Gold        12008
13           114    Male   33    Los Angeles          Silver        82075
14           115  Female   42        Chicago          Bronze         5304
15           116    Male   29  San Francisco            Gold        13602
16           117    Male   26          Miami          Silver         7006
17           118  Female   38        Houston          Bronze         4509
18           119  Female   32       New York            Gold        11703
19           120    Male   34    Los Angeles          Silver         7902
20           121  Female   43        Chicago          Bronze        50575
21           122    Male   30  San Francisco            Gold        14705
22           123    Male   27          Miami          Silver         7104
23           124  Female   37        Houston          Bronze         4308
24           125  Female   31       New York            Gold        11406
25           126    Male   35    Los Angeles          Silver         8109
26           127  Female   41        Chicago          Bronze        48525
27           128    Male   28  San Francisco            Gold        15001
28           129    Male   32          Miami          Silver         6703
29           130  Female   36        Houston          Bronze         4605
30           131  Female   30       New York            Gold        11908
31           132    Male   33    Los Angeles          Silver        83075
33           134    Male   29  San Francisco            Gold        13702
34           135    Male   26          Miami          Silver         6906
35           136  Female   38        Houston          Bronze         4409
36           137  Female   32       New York            Gold        11603
41           142  Female   37        Houston          Bronze         4208
47           148  Female   36        Houston          Bronze         4705
48           149  Female   30       New York            Gold        11808
71           172  Female   37        Houston          Bronze         4208
143          244  Female   37        Houston          Bronze         4308
200          301    Male   36  San Francisco            Gold        14208
201          302  Female   29          Miami          Silver         7304
202          303  Female   35        Houston          Bronze         4506
203          304    Male   31       New York            Gold        12106
204          305    Male   27    Los Angeles          Silver         7809
205          306  Female   42        Chicago          Bronze        49525
209          310  Female   32       New York            Gold        11703
211          312  Female   43        Chicago          Bronze        51575
244          345  Female   37        Houston          Bronze         4408
254          355    Male   30  San Francisco            Gold        14405
270          371    Male   35    Los Angeles          Silver         8009
276          377    Male   33    Los Angeles          Silver         7702
300          401    Male   33    Los Angeles          Silver         8002
324          425    Male   34    Los Angeles          Silver         7802

     Items Purchased  Average Rating  Discount Applied  \
0                 14              46              True
1                 11              41             False
2                  9              34              True
3                 19              47             False
4                 13              40              True
5                  8              31             False
6                 15              45              True
7                 12              42             False
8                 10              36              True
9                 21              48             False
10                11              38              True
11                 7              32             False
12                16              43              True
13                13              44             False
14                 9              35              True
15                18              49             False
16                12              37              True
17                 8              30             False
18                14              47              True
19                11              40             False
20                10              33              True
21                20              48             False
22                13              41              True
23                 7              34             False
24                15              46              True
25                12              43             False
26                 9              36              True
27                21              49             False
28                10              38              True
29                 8              31             False
30                16              45              True
31                13              42             False
33                18              47             False
34                12              39              True
35                 8              32             False
36                14              44              True
41                 7              31             False
47                 8              30             False
48                16              47              True
71                 7              31             False
143                7              34             False
200               19              46             False
201               14              40              True
202                7              33             False
203               17              48              True
204               11              42             False
205               10              35              True
209               14              45              True
211                9              33              True
244                7              32             False
254               19              46             False
270               12              41             False
276               11              42             False
300               11              41             False
324               11              42             False

     Days Since Last Purchase Satisfaction Level
0                          25          Satisfied
1                          18            Neutral
2                          42        Unsatisfied
3                          12          Satisfied
4                          55        Unsatisfied
5                          22            Neutral
6                          28          Satisfied
7                          14            Neutral
8                          40        Unsatisfied
9                           9          Satisfied
10                         34        Unsatisfied
11                         20            Neutral
12                         21          Satisfied
13                         15          Satisfied
14                         38        Unsatisfied
15                         11          Satisfied
16                         48        Unsatisfied
17                         25            Neutral
18                         29          Satisfied
19                         16            Neutral
20                         41        Unsatisfied
21                         13          Satisfied
22                         54        Unsatisfied
23                         23            Neutral
24                         27          Satisfied
25                         13            Neutral
26                         39        Unsatisfied
27                         10          Satisfied
28                         33        Unsatisfied
29                         19            Neutral
30                         20          Satisfied
31                         14          Satisfied
33                         10          Satisfied
34                         47        Unsatisfied
35                         24            Neutral
36                         22          Satisfied
41                         21            Neutral
47                         18            Neutral
48                         19          Satisfied
71                         21            Unknown
143                        23            Unknown
200                        11          Satisfied
201                        50        Unsatisfied
202                        21            Neutral
203                        18          Satisfied
204                        16            Neutral
205                        35        Unsatisfied
209                        21          Satisfied
211                        38        Unsatisfied
244                        25            Neutral
254                        12          Satisfied
270                        17            Neutral
276                        18            Neutral
300                        18            Neutral
324                        18            Neutral

In [12]:
df.drop_duplicates(subset=cols_to_check, keep='first', inplace=True)
df.to_csv("data.csv", index=False)